### ISSUE TITLE
Focus tag input field

### ISSUE THREAD

**Issue by jesus2099** [zabe40/musicbrainz-userscripts#1]
I am not a user of `bandcamp-tag-importer.user.js` but based on [this screenshot](https://community.metabrainz.org/t/a-new-musicbrainz-user-script-was-released/77897/65?u=jesus2099), it seems that it would be nice if you could focus the tag input field after filling it.

This way one could directly move the caret inside there and even **press enter to submit the tags**, without using a second mous click.

**Comment by zabe40** [comment]
Thanks for the idea!
