### ISSUE TITLE
show an indicator on event pages

### ISSUE THREAD

**Issue by UltimateRiff** [zabe40/musicbrainz-userscripts#14]
with the Event Art Archive working its way through beta, I think it would be good to show an indicator when an image comes from a URL to prevent confusion (and hopefully promoting uploading posters to EAA). could be something like a colored border around the image and/or text that says the poster can be uploaded to EAA?

(see also my [confused ticket comment](https://tickets.metabrainz.org/browse/MBS-13600?focusedId=72311&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-72311), lol)

**Comment by zabe40** [comment]
Obsoleted by #17.
