### ISSUE TITLE
prevent double-images on Event pages

### ISSUE THREAD

**Issue by UltimateRiff** [zabe40/musicbrainz-userscripts#15]
another EAA ticket, when an event has both uploaded and linked art, this script will put the URL art right above the uploaded art. in theory, only one of these should be shown (example event [Coltchella 4](https://beta.musicbrainz.org/event/d8877684-34ce-462a-8215-3b922c61ea55))

![image](https://github.com/zabe40/musicbrainz-userscripts/assets/100507157/b79d4e34-e160-4523-8830-a1a0df9a0a8a)

edit: since EAA is currently in beta, I'd imagine there's a chance there might be some changes between now and the proper release, so I understand if you wanna wait until then~

**Comment by zabe40** [comment]
Now that EAA is available and the [poster relationship is depreciated](https://musicbrainz.org/relationship/ca7ada80-bf87-4422-9671-ec0a22733acc) I'm thinking I might just remove support for event pages entirely. The people who want to migrate these relationships to the EAA can use [the depreciated relationship URL report](https://musicbrainz.org/report/DeprecatedRelationshipURLs). How does that sound?

**Comment by UltimateRiff** [comment]
that sounds like a plan to me~

**Comment by jesus2099** [comment]
I made a patch, if you want to review it: 

- #17
