### ISSUE TITLE
Auto-update doesn't work

### ISSUE THREAD

**Issue by jesus2099** [zabe40/musicbrainz-userscripts#18]
I'm on:

- Winows 10 Vivaldi 6.8.3381.48 (Chrome 126) Violentmonkey 2.20.0
- Android 9 Kiwi Browser (Chrome) 124.0.6327.4

I have Entity Images version `2024-03-30` installed on both, and it doesn't detect [version `2024-07-22`](https://github.com/zabe40/musicbrainz-userscripts/commit/59b9f13d211f87309b05f871d5e6111f837408d0) as being a more recent version, neither by itself nor when I click the update button.

See https://github.com/jesus2099/konami-command/pull/1#issuecomment-366431040
You should use versions such as `2024.7.22` with no heading zeroes and 4 elements `2024.7.22.2209` maximum.

**Comment by zabe40** [comment]
> [I can revisit this if its a problem for someone in the future](https://github.com/zabe40/musicbrainz-userscripts/pull/2#issuecomment-1901701050)

Alright then, looks like the future is here sooner than I thought lol

**Comment by jesus2099** [comment]
Thanks!

**Comment by jesus2099** [comment]
I told the potential users, [in the forum](https://community.metabrainz.org/t/a-new-musicbrainz-user-script-was-released/77897/78?u=jesus2099), to manually update their scripts now.
