### ISSUE TITLE
Canonicalizer: Cleaned up URL doesn't update

### ISSUE THREAD

**Issue by zabe40** [zabe40/musicbrainz-userscripts#3]
After pressing the "Canonicalize URL" button, the dialog opens and the new URL is put into the input element, but the corresponding "Cleaned up URL" does not update. I've tried dispatching KeyboardEvents and InputEvents to the input field, but neither were successful.

![Screenshot 2024-01-22 at 14-57-12 Irokz - Edit - MusicBrainz](https://github.com/zabe40/musicbrainz-userscripts/assets/88987866/d3d2a99f-07c6-4624-a350-1ca44177917d)

**Comment by zabe40** [comment]
Thanks for the tip! I tried to include this the easy way with 
```javascript
// @require      https://raw.github.com/kellnerd/es-utils/v0.1.3/dom/react.js
```
but ended up with
```
Uncaught SyntaxError: export declarations may only appear at top level of a module
```

It works fine just copy-pasted into the code though (with the `export` keyword removed). It looks like you get around this in your userscripts with your userscript-bundler, would you recommend this over copy-pasting?

**Comment by kellnerd** [comment]
Whatever fits your needs the best :)
If you only need that single function, it's better to just copy it and save yourself the additional build step. But if you want to develop larger userscripts in multiple modules instead of one giant script file, or plan to integrate more third party code, you can give the userscript-bundler a try.

**Comment by zabe40** [comment]
I think I'm going to use the bundler, since I have plans for a larger userscript soon, but would you consider distributing es-utils in a format suitable for `@require` -ing (i.e. with the `export`s stripped)? It might be useful for smaller userscripts like this one that just need a single function from a library and could then get the best of both worlds, so the dependencies are updated without the need for a build step.

**Comment by kellnerd** [comment]
It is unlikely that I am going to do that as long there is no actual demand for it.
As far as I am aware es-utils is only used by my own projects. It's mainly a solution for my problem that I tended to copy these small functions from project to project.
(There are lots of dedicated libraries which would achieve the same and more for one of these functions, but I personally prefer to have a minimal amount of code. Hence I have written my own utilities which work for me but might not work as good in other scenarios.)

**Comment by zabe40** [comment]
Ah yeah that makes sense.
